version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production  # Set Flask environment to production
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"  # Map to port 80 of nginx in frontend container
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: your_database_name
