name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test_backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      
      - name: Run backend tests
        run: |
          cd backend
          # Add your backend test command here

  build_and_test_frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      
      - name: Run frontend tests
        run: |
          cd frontend
          # Add your frontend test command here

  build_and_push_docker_images:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [build_and_test_backend, build_and_test_frontend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend Docker image
        run: |
          docker build -t <YOUR_DOCKER_USERNAME>/<YOUR_BACKEND_APP_NAME>:latest backend/
          docker push <YOUR_DOCKER_USERNAME>/<YOUR_BACKEND_APP_NAME>:latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t <YOUR_DOCKER_USERNAME>/<YOUR_FRONTEND_APP_NAME>:latest frontend/
          docker push <YOUR_DOCKER_USERNAME>/<YOUR_FRONTEND_APP_NAME>:latest
